// HTML for the service pages and the services hub. `root` is the relative
// path back to the site folder, so links work under /sites/faircloth-roofing/.
import { site } from './site.mjs';

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const strip = s => String(s).replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
// JSON-LD inside <script>: escape "<" so text can never close the tag.
const ld = obj => `<script type="application/ld+json">${JSON.stringify(obj).replace(/</g, '\\u003c')}</script>`;

const ICON = {
  phone: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.6 10.8a15.1 15.1 0 0 0 6.6 6.6l2.2-2.2a1 1 0 0 1 1-.25 11.4 11.4 0 0 0 3.6.57 1 1 0 0 1 1 1V20a1 1 0 0 1-1 1A17 17 0 0 1 3 4a1 1 0 0 1 1-1h3.5a1 1 0 0 1 1 1c0 1.25.2 2.45.57 3.57a1 1 0 0 1-.25 1z"/></svg>',
  arrow: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',
  logo: (bg, inner) => `<svg viewBox="0 0 48 48" aria-hidden="true"><rect width="48" height="48" rx="6" fill="${bg}"/><path d="M7 28 24 13l17 15" fill="none" stroke="#fff" stroke-width="4.2" stroke-linecap="square"/><path d="M14 32 24 23.5 34 32" fill="none" stroke="${inner}" stroke-width="3.6" stroke-linecap="square"/>${bg === '#1D1160' ? '<path d="M20 38h8" stroke="#A1A1A4" stroke-width="3.2"/>' : ''}</svg>`
};

const business = {
  '@type': 'RoofingContractor',
  '@id': site.baseUrl + '#business',
  name: site.name,
  url: site.baseUrl,
  telephone: site.phone,
  address: { '@type': 'PostalAddress', addressLocality: site.city, addressRegion: site.state, addressCountry: 'US' },
  geo: { '@type': 'GeoCoordinates', latitude: site.geo[0], longitude: site.geo[1] },
  areaServed: { '@type': 'GeoCircle', geoMidpoint: { '@type': 'GeoCoordinates', latitude: site.geo[0], longitude: site.geo[1] }, geoRadius: Math.round(site.radiusMiles * 1609.344) }
};

function layout({ root, path, title, description, image, current, services, credits, jsonld, main }) {
  const url = site.baseUrl + path;
  const nav = services.map(s => `<a href="${root}services/${s.slug}/"${s.slug === current ? ' aria-current="page"' : ''}>${esc(s.name)}</a>`).join('');
  const creditLine = credits.map(([t, by, lic, href]) => `<a href="${esc(href)}" rel="noopener">${esc(t)}</a> by ${esc(by)} (${esc(lic)})`).join('; ');
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)} | ${esc(site.name)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="${esc(site.name)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${url}">
${image ? `<meta property="og:image" content="${site.baseUrl}${image.src}">\n<link rel="preload" as="image" href="${root}${image.src}">\n` : ''}<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=Barlow:wght@400;500;600;700&display=swap">
<link rel="stylesheet" href="${root}assets/service.css">
${jsonld.map(ld).join('\n')}
</head>
<body>
<!-- Generated by _build/build.mjs from _build/services.mjs. Edit those, not this file. -->

<div class="strip">
  <div class="wrap">
    <span><span class="demo">Demo site</span> <span class="hide-sm">Phone, prices and figures marked DEMO are placeholders.</span></span>
    <span>Mon–Sat · <b>24/7 storm emergencies</b> <span class="demo">demo</span></span>
  </div>
</div>

<header class="site">
  <div class="wrap">
    <a class="brand" href="${root}" aria-label="${esc(site.name)} home">
      ${ICON.logo('#1D1160', '#00A3B5')}
      <span><b>${esc(site.name)}</b><small>${esc(site.city)} · ${site.state}</small></span>
    </a>
    <nav class="main" aria-label="Main">
      ${nav}<a href="${root}#storm">Storm claims</a><a href="${root}#estimate">Estimate</a>
    </nav>
    <a class="btn btn-teal hdr-call" href="${site.phoneHref}" aria-label="Call ${site.phone}, demo number">${ICON.phone}${site.phone}</a>
    <button class="icon-btn" id="themeBtn" type="button" aria-label="Color theme: system">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 0 0 18z" fill="currentColor"/></svg>
    </button>
    <details class="menu">
      <summary class="icon-btn" aria-label="Open menu"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg></summary>
      <div class="panel">
        <a href="${root}">Home</a><a href="${root}services/">All services</a>${nav}<a href="${root}#storm">Storm &amp; insurance</a><a href="${root}#estimate">Instant estimate</a><a href="${root}#contact">Free inspection</a>
      </div>
    </details>
  </div>
</header>

<main>
${main}
</main>

<footer class="site">
  <div class="wrap">
    <div>
      <a class="brand" href="${root}">${ICON.logo('#00788C', '#1D1160')}<span><b>${esc(site.name)}</b><small>${esc(site.city)} · ${site.state}</small></span></a>
      <p style="margin-top:14px;max-width:40ch">Roofing, gutters and siding for ${esc(site.city)}, Fort Bragg and ${esc(site.region)}.</p>
    </div>
    <div><h4>Services</h4><ul><li><a href="${root}services/">All services</a></li>${services.map(s => `<li><a href="${root}services/${s.slug}/">${esc(s.name)}</a></li>`).join('')}</ul></div>
    <div><h4>Explore</h4><ul><li><a href="${root}#storm">Storm &amp; insurance</a></li><li><a href="${root}#estimate">Instant estimate</a></li><li><a href="${root}#areas">Service area</a></li><li><a href="${root}#faq">FAQ</a></li></ul></div>
    <div><h4>Contact <span class="demo">demo</span></h4><ul><li><a href="${site.phoneHref}">${site.phone}</a></li><li>${esc(site.email)}</li><li>${esc(site.city)}, ${site.state}</li></ul></div>
    <p class="legal">© <span id="yr">2026</span> ${esc(site.name)}. Demo website: phone, email, prices, discounts and company figures are placeholders.${creditLine ? ` Photos via Wikimedia Commons: ${creditLine}.` : ''}</p>
  </div>
</footer>

<nav class="callbar" aria-label="Quick contact">
  <a href="${site.phoneHref}">${ICON.phone}Call now</a>
  <a class="go" href="${root}#contact">Free inspection</a>
</nav>

<script src="${root}assets/service.js"></script>
</body>
</html>
`;
}

function townsSection(heading, lede) {
  return `<section aria-labelledby="towns-title">
  <div class="wrap">
    <div class="sec-head">
      <p class="kicker">Service area</p>
      <h2 id="towns-title">${heading}</h2>
      <p class="lede">${lede}</p>
    </div>
    <div class="towns">
      ${site.towns.map(([county, towns]) => `<div><h3>${esc(county)}${county.includes('&') ? ' counties' : ' County'}</h3><p>${towns.map(esc).join(' · ')}</p></div>`).join('\n      ')}
    </div>
  </div>
</section>`;
}

function card(s, root, headingTag = 'h3') {
  return `<a class="card" href="${root}services/${s.slug}/">
        <figure><img src="${root}${s.image.src}" alt="" loading="lazy" width="${s.image.w}" height="${s.image.h}"></figure>
        <div class="body"><${headingTag}>${esc(s.name)}</${headingTag}><p>${s.sub}</p><span class="more">${esc(s.name)} details →</span></div>
      </a>`;
}

function ctaBand(root, heading) {
  return `<section class="cta" aria-label="Book a free inspection">
  <div class="wrap">
    <div><h2>${heading}</h2><p>Free inspection and written quote, usually within one business day.</p></div>
    <div class="btns">
      <a class="btn btn-white" href="${root}#contact">Book free inspection ${ICON.arrow}</a>
      <a class="btn btn-line" href="${site.phoneHref}">${ICON.phone}${site.phone} <span class="demo">demo</span></a>
    </div>
  </div>
</section>`;
}

export function servicePage(s, all) {
  const root = '../../';
  const path = `services/${s.slug}/`;
  const url = site.baseUrl + path;
  const related = s.related.map(slug => all.find(x => x.slug === slug));
  const towns = site.towns.flatMap(([, t]) => t);

  const jsonld = [
    { '@context': 'https://schema.org', ...business },
    {
      '@context': 'https://schema.org',
      '@type': 'Service',
      '@id': url + '#service',
      name: strip(s.title),
      serviceType: s.serviceType,
      description: s.description,
      url,
      image: site.baseUrl + s.image.src,
      provider: { '@id': business['@id'] },
      areaServed: towns.map(name => ({ '@type': 'City', name: `${name}, ${site.state}` })),
      hasOfferCatalog: {
        '@type': 'OfferCatalog',
        name: strip(s.options.title),
        itemListElement: s.options.rows.map(([name, desc]) => ({ '@type': 'Offer', itemOffered: { '@type': 'Service', name: strip(name), description: strip(desc) } }))
      }
    },
    {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: site.baseUrl },
        { '@type': 'ListItem', position: 2, name: 'Services', item: site.baseUrl + 'services/' },
        { '@type': 'ListItem', position: 3, name: s.name, item: url }
      ]
    },
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: s.faq.map(([q, a]) => ({ '@type': 'Question', name: strip(q), acceptedAnswer: { '@type': 'Answer', text: strip(a.replace(/<span class="demo">demo<\/span>/g, '')) } }))
    }
  ];

  const main = `<nav class="crumbs" aria-label="Breadcrumb"><div class="wrap"><ol>
  <li><a href="${root}">Home</a></li><li><a href="${root}services/">Services</a></li><li><span aria-current="page">${esc(s.name)}</span></li>
</ol></div></nav>

<section class="p-hero" aria-labelledby="page-title">
  <div class="wrap">
    <div class="copy">
      <p class="kicker">${esc(s.kicker)}</p>
      <h1 id="page-title">${s.h1}</h1>
      <p class="sub">${s.sub}</p>
      <div class="ctas">
        <a class="btn btn-teal" href="${root}#contact">Free inspection ${ICON.arrow}</a>
        <a class="btn btn-line" href="${site.phoneHref}">${ICON.phone}Call ${site.phone}</a>
      </div>
    </div>
    <figure><img src="${root}${s.image.src}" alt="${esc(s.image.alt)}" width="${s.image.w}" height="${s.image.h}" fetchpriority="high"></figure>
  </div>
</section>

<section aria-labelledby="about-title">
  <div class="wrap two">
    <div class="prose">
      <p class="kicker">${esc(s.name)} in ${esc(site.city)}</p>
      <h2 id="about-title">What you get</h2>
      ${s.intro.map(p => `<p>${p}</p>`).join('\n      ')}
    </div>
    <div class="box">
      <h3>${s.includedTitle}</h3>
      <ul class="checks">
        ${s.included.map(([b, t]) => `<li><span><b>${b}</b> ${t}</span></li>`).join('\n        ')}
      </ul>
    </div>
  </div>
</section>

<section class="alt" aria-labelledby="opts-title">
  <div class="wrap">
    <div class="sec-head">
      <p class="kicker">Options &amp; pricing <span class="demo">demo</span></p>
      <h2 id="opts-title">${s.options.title}</h2>
    </div>
    <div class="table-wrap">
      <table class="opts">
        <thead><tr><th scope="col">Option</th><th scope="col">Best for</th><th scope="col">Lifespan</th><th scope="col">Installed</th></tr></thead>
        <tbody>
          ${s.options.rows.map(([n, d, l, p]) => `<tr><td><b>${n}</b></td><td>${d}</td><td>${l}</td><td>${p}</td></tr>`).join('\n          ')}
        </tbody>
      </table>
    </div>
    <p class="note" style="margin-top:12px">${s.options.note}</p>
  </div>
</section>

<section aria-labelledby="signs-title">
  <div class="wrap two">
    <div>
      <div class="sec-head" style="margin-bottom:24px">
        <p class="kicker">Warning signs</p>
        <h2 id="signs-title">${s.signsTitle}</h2>
      </div>
      <ul class="checks warn">
        ${s.signs.map(([b, t]) => `<li><span><b>${b}</b> ${t}</span></li>`).join('\n        ')}
      </ul>
    </div>
    <div>
      <div class="sec-head" style="margin-bottom:24px">
        <p class="kicker">How it works</p>
        <h2>Start to finish</h2>
      </div>
      <ol class="steps">
        ${s.steps.map(([h, p]) => `<li><div><h3>${h}</h3><p>${p}</p></div></li>`).join('\n        ')}
      </ol>
    </div>
  </div>
</section>

<section class="local" aria-labelledby="local-title">
  <div class="wrap">
    <div class="sec-head">
      <p class="kicker">Local know-how</p>
      <h2 id="local-title">${s.local.title}</h2>
    </div>
    <div class="cols">
      ${s.local.paras.map(p => `<p>${p}</p>`).join('\n      ')}
    </div>
  </div>
</section>

<section class="alt" aria-labelledby="faq-title">
  <div class="wrap faq-grid">
    <div class="sec-head">
      <p class="kicker">FAQ</p>
      <h2 id="faq-title">${esc(s.name)} questions</h2>
      <p class="lede">Don't see yours? Call and a real person will answer.</p>
    </div>
    <div>
      ${s.faq.map(([q, a]) => `<details class="q"><summary>${q}</summary><p>${a}</p></details>`).join('\n      ')}
    </div>
  </div>
</section>

${townsSection(`${esc(s.name)} across ${esc(site.city)} and ${site.radiusMiles} miles out`, `We serve ${esc(site.city)} and every town within about ${site.radiusMiles} miles, from Sanford to Lumberton and Southern Pines to Clinton.`)}

<section class="alt" aria-labelledby="related-title">
  <div class="wrap">
    <div class="sec-head">
      <p class="kicker">Related services</p>
      <h2 id="related-title">Often done together</h2>
    </div>
    <div class="cards">
      ${related.map(r => card(r, root)).join('\n      ')}
    </div>
  </div>
</section>

${ctaBand(root, `Get a ${esc(s.name.toLowerCase())} quote`)}`;

  return layout({ root, path, title: s.title, description: s.description, image: s.image, current: s.slug, services: all, credits: [s.image.credit, ...related.map(r => r.image.credit)], jsonld, main });
}

export function hubPage(all) {
  const root = '../';
  const path = 'services/';
  const title = `Roofing, Gutter & Siding Services in ${site.city}, ${site.state}`;
  const description = `Roof replacement and repair, seamless gutters and siding for homes and businesses in ${site.city}, ${site.state} and towns within ${site.radiusMiles} miles. Free inspections.`;
  const jsonld = [
    { '@context': 'https://schema.org', ...business },
    {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: site.baseUrl },
        { '@type': 'ListItem', position: 2, name: 'Services', item: site.baseUrl + path }
      ]
    }
  ];
  const main = `<nav class="crumbs" aria-label="Breadcrumb"><div class="wrap"><ol>
  <li><a href="${root}">Home</a></li><li><span aria-current="page">Services</span></li>
</ol></div></nav>

<section aria-labelledby="page-title">
  <div class="wrap">
    <div class="sec-head">
      <p class="kicker">${esc(site.city)}, ${site.state} · Services</p>
      <h1 id="page-title" style="font-size:clamp(2.6rem,7vw,4.4rem);text-transform:uppercase;font-weight:800">Roofing, gutters &amp; siding</h1>
      <p class="lede">The whole outside of your house, from one local crew. Every job starts with a free inspection and a written quote with photos.</p>
    </div>
    <div class="cards three">
      ${all.map(s => card(s, root, 'h2')).join('\n      ')}
    </div>
  </div>
</section>

${townsSection(`Serving ${esc(site.city)} and ${site.radiusMiles} miles out`, `Straight-line distances and the full town list are on the <a href="${root}#areas">home page</a>.`)}

${ctaBand(root, 'Not sure what you need?')}`;

  return layout({ root, path, title, description, image: all[0].image, current: null, services: all, credits: all.map(s => s.image.credit), jsonld, main });
}

export function sitemap(all) {
  const urls = ['', 'services/', ...all.map(s => `services/${s.slug}/`)];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${site.baseUrl}${u}</loc></url>`).join('\n')}
</urlset>
`;
}
